oid4vp.proxy.enabled=true
oid4vp.proxy.host=localhost
oid4vp.proxy.port=8888
oid4vp.enabled=true
oid4vp.clientId=dsp
oid4vp.scope=openid
oid4vp.trustAll=true
oid4vp.holder.id=did:key:zDnaehXH4gDLjLeWcACPyQX9TnvsKiQNt6KT7fdsfyW6fhEYA
oid4vp.holder.kid=did:key:zDnaehXH4gDLjLeWcACPyQX9TnvsKiQNt6KT7fdsfyW6fhEYA
oid4vp.holder.key.type=EC
oid4vp.holder.key.path=oid4vp/private-key.pem
oid4vp.holder.signatureAlgorithm=ECDH-ES
oid4vp.credentialsFolder=oid4vp/credentials
oid4vp.trustAnchorsFolder=oid4vp/trustAnchors
oid4vp.organizationClaim=verifiableCredential.issuer

fdscTransfer.enabled=false
fdscTransfer.credentialsConfigAddress=http://provider-ccs.127.0.0.1.nip.io:8080
fdscTransfer.transferHost=mp-data-service.127.0.0.1.nip.io
fdscTransfer.verifierHost=https://verifier.mp-operations.org
fdscTransfer.verifierInternalHost=verifier:3000
fdscTransfer.opaHost=http://localhost:8181
fdscTransfer.apisix.address=http://localhost:9180
fdscTransfer.apisix.token=admin
fdscTransfer.apisix.httpsProxy=http://squid-proxy.infra.svc.cluster.local:8888

testExtension.enabled=false
testExtension.controller.enabled=false
testExtension.controller.port=8687
testExtension.controller.path=/tck
testExtension.identity.enabled=false

tmfExtension.enabled=true
tmfExtension.quoteApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/quote/v4
tmfExtension.agreementApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/agreementManagement/v4
tmfExtension.productOrderApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/productOrderingManagement/v4
tmfExtension.productCatalogApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/productCatalogManagement/v4
tmfExtension.productInventoryApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/productInventory/v4
tmfExtension.usageManagementApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/usageManagement/v4
tmfExtension.partyCatalogApi=http://consumer-tmf.127.0.0.1.nip.io:8080/tmf-api/party/v4
tmfExtension.catalog.enabled=true

edc.participant.id=did:web:fancy-marketplace.biz
edc.log.level=DEBUG
edc.jsonld.https.enabled=true
edc.jsonld.http.enabled=true
edc.negotiation.state.machine.iteration.wait.millis=5
edc.hostname=local-host

web.http.port=7080
web.http.path=/api
web.http.management.port=9191
web.http.management.path=/api/v1/management
web.http.protocol.path=/api/dsp
web.http.protocol.port=8081
web.http.control.path=/api/control
web.http.control.port=8082
web.http.catalog.path=/api/catalog
web.http.catalog.port=8083
web.http.version.path=/api/version
web.http.version.port=8084

default.http.https.resolution=true

